apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tf-atom-lambda-function-aws
  description: "Terraform atom: AWS Lambda Function - creates a single Lambda function"
  annotations:
    github.com/project-slug: PlatformStackPulse/tf-atom-lambda-function-aws
    backstage.io/techdocs-ref: dir:.
  tags: [terraform, aws, atom]
  links:
    - url: https://github.com/PlatformStackPulse/tf-atom-lambda-function-aws
      title: GitHub Repository
      icon: github
spec:
  type: terraform-module
  lifecycle: production
  owner: platform-team
  system: terraform-atoms
